- import_playbook: init-python.yml
- import_playbook: disclose-hostname.yml
- import_playbook: install-ssh-key.yml
- import_playbook: init-manifest-template.yml
- import_playbook: init-apiserver-endpoint.yml
- import_playbook: init-cri.yml
- import_playbook: load-image.yml
- import_playbook: install-cni.yml
- import_playbook: install-kube-release.yml

- name: Prepare resources
  hosts: nodes
  tasks:
    - import_role:
        name: net-plugin
        tasks_from: prepare

- import_playbook: deploy-node.yml